services:
  private-stream-ui:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
      CONFIG_PATH: "/config.json"
    volumes:
      - ./config.json:/config.json:ro
