apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-stream-ui.fullname" . }}-config
  labels:
    {{- include "private-stream-ui.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toJson .Values.config | nindent 4 }}
