apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-stream-ui.fullname" . }}
  labels:
    {{- include "private-stream-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "private-stream-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ tpl (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "private-stream-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "private-stream-ui.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config.json
              subPath: config.json
              readOnly: true
          {{- if .Values.oidc.enabled }}
            - name: oidc
              mountPath: {{ printf "/config.json.d/%s" .Values.oidc.secretKey }}
              subPath: {{ .Values.oidc.secretKey }}
              readOnly: true
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: production
            - name: CONFIG_PATH
              value: "/config.json"
            - name: DB_HOSTNAME
              value: {{ .Values.databaseConfig.host | quote }}
            - name: DB_PORT
              value: {{ .Values.databaseConfig.port | quote }}
            - name: DB_DATABASE
              value: {{ .Values.databaseConfig.database | quote }}
          {{- if .Values.databaseConfig.auth.enabled }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "private-stream-ui.secretNameDb" . | quote }}
                  key: {{ .Values.databaseConfig.auth.usernameKey | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "private-stream-ui.secretNameDb" . | quote }}
                  key: {{ .Values.databaseConfig.auth.passwordKey | quote }}
          {{- end }}
            - name: DB_MAX_CONNECTIONS
              value: {{ .Values.databaseConfig.maxConnections | quote }}
            - name: DB_IDLE_TIMEOUT
              value: {{ .Values.databaseConfig.idleTimeout | quote }}
            - name: DB_MAX_LIFETIME
              value: {{ .Values.databaseConfig.maxLifetime | quote }}
            - name: DB_CONNECTION_TIMEOUT
              value: {{ .Values.databaseConfig.connectionTimeout | quote }}
          {{- if .Values.oidc.enabled }}
            - name: OIDC_SECRET_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "private-stream-ui.secretNameOidc" . | quote }}
                  key: {{ .Values.oidc.localSecret.secretGeneratedKey | quote }}
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "private-stream-ui.fullname" . }}-config
        {{- if .Values.oidc.enabled }}
        - name: oidc
          secret:
            secretName: {{ include "private-stream-ui.secretNameOidcPrimary" . }}
            items:
              - key: {{ .Values.oidc.secretKey }}
                path: {{ .Values.oidc.secretKey }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
